name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag meyersh/tcrp:$(git rev-parse --short main)
        docker tag meyersh/tcrp:$(git rev-parse --short main) meyersh/tcrp:latest
